services:
    security.authentication_rest_handler:
        class: TravelDiary\RestBundle\Security\AuthenticationRestHandler

    user_by_request_resolver:
        class: TravelDiary\RestBundle\Service\User\UserByRequestResolver
        calls:
            - [setContainer, ['@service_container']]
