<?php

namespace TravelDiary\TripBundle\Entity;

use Doctrine\ORM\EntityRepository;
use FOS\UserBundle\Model\UserInterface;

/**
 * TripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripRepository extends EntityRepository
{
    public function getMyTrips(UserInterface $user)
    {
        return $this->createQueryBuilder('trip')
            ->where('trip.user = :user')
            ->andWhere('trip.isFuture <> 1')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }
}
