td_place:
    resource: "@TDPlaceBundle/Resources/config/routing.yml"
    prefix:   /

td_trip:
    resource: "@TDTripBundle/Resources/config/routing.yml"
    prefix:   /trip

td_dashboard:
    resource: "@TDDashboardBundle/Resources/config/routing.yml"
    prefix:   /

td_user:
    resource: "@FOSUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


