td_rest:
    type:     rest
    resource: TravelDiary\RestBundle\Controller\TripController
    prefix:   /api/v1/

td_rest_place:
    type:     rest
    resource: TravelDiary\RestBundle\Controller\PlaceController
    prefix:   /api/v1/

td_place:
    resource: "@TDPlaceBundle/Resources/config/routing.yml"
    prefix:   /

td_trip:
    resource: "@TDTripBundle/Resources/config/routing.yml"
    prefix:   /trip

td_dashboard:
    resource: "@TDDashboardBundle/Resources/config/routing.yml"
    prefix:   /

td_user:
    resource: "@FOSUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: /api/v1/login_check


