security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        rest:
            pattern: ^/rest
            form_login:
                check_path: /rest/login
                provider: fos_userbundle
                failure_handler: security.authentication_rest_handler
                success_handler: security.authentication_rest_handler
                username_parameter: login
                password_parameter: password

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/trip, role: ROLE_USER }

