TravelDiary\RatingBundle\Entity\UserLikesPlaces:
    type: entity
    table: user_likes_places
    repositoryClass: TravelDiary\RatingBundle\Entity\UserLikesPlacesRepository
    id:
        id:
            type: bigint
            options:
                unsigned: true
            generator:
                strategy: AUTO
    fields:
        created:
            type: date
    manyToOne:
        user:
            targetEntity: TravelDiary\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
        place:
            targetEntity: TravelDiary\PlaceBundle\Entity\Place
            joinColumn:
                name: place_id
                referencedColumnName: id
                onDelete: CASCADE

