TravelDiary\PlaceBundle\Entity\FuturePlaces:
    type: entity
    table: future_places
    repositoryClass: TravelDiary\PlaceBundle\Entity\FuturePlacesRepository
    id:
        id:
            type: bigint
            options:
                unsigned: true
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: TravelDiary\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
        futurePlace:
            targetEntity: TravelDiary\PlaceBundle\Entity\Place
            joinColumn:
                name: future_place_id
                referencedColumnName: id
                onDelete: CASCADE
        originalPlace:
            targetEntity: TravelDiary\PlaceBundle\Entity\Place
            joinColumn:
                name: original_place_id
                referencedColumnName: id
                onDelete: CASCADE

