<?php

namespace TravelDiary\PlaceBundle\Entity;

/**
 * FuturePlacesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuturePlacesRepository extends \Doctrine\ORM\EntityRepository
{
}
