<?php

namespace TravelDiary\PlaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends EntityRepository
{
    public function findByCityIdAndUser($cityId = null, $user = null)
    {
        $q = $this->createQueryBuilder('place')
            ->leftJoin('place.trip', 'trip')
            ->where('trip.isFuture IS NULL');

        if (0 < (int) $cityId) {
            $q
                ->andWhere('place.city = :cityId')
                ->setParameter('cityId', $cityId);
        }

        if (null !== $user) {
            $q
                ->andWhere('place.user = :user')
                ->setParameter('user', $user);
        }

        return $q
            ->orderBy('place.likes', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
