<?php

namespace TravelDiary\PlaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends EntityRepository
{
    public function findAllTopPlaces()
    {
        return $this->createQueryBuilder('place')
            ->orderBy('place.likes', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
